version: '3'

services:
  demo-db:
    image: postgres:15.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=energy-db
    ports:
      - "5431:5431"
  demo-be:
    build: .
    image: spring_server4
    restart: always
    environment:
      - TZ=UTC
      - DB_PASSWORD=1234
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_DBNAME=energy-db
      - DB_IP=spring-demo-demo-db-1
    ports:
        - "8080:8080"
    depends_on:
         - demo-db


   

